apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.database.deploymentName }}
  labels:
    module: db-postgres
spec:
  serviceName: {{ .Values.database.headlessServiceName }}
  replicas: {{ .Values.database.replicas }}
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      module: db-postgres
  template:
    metadata:
      labels:
        module: db-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.database.containerPort }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.database.auth.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.auth.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.database.auth.database | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: init-sql
          configMap:
            name: {{ .Values.database.initConfigMapName }}
{{- if not .Values.database.persistence.enabled }}
        - name: pgdata
          emptyDir: {}
{{- end }}
{{- if .Values.database.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes:
{{ toYaml .Values.database.persistence.accessModes | indent 10 }}
{{- if .Values.database.persistence.storageClass }}
        storageClassName: {{ .Values.database.persistence.storageClass | quote }}
{{- end }}
        resources:
          requests:
            storage: {{ .Values.database.persistence.size | quote }}
{{- end }}
